/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user, tenant, business date, permissions and enabled modules */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/business-day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get business day */
        get: operations["getBusinessDay"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List branches */
        get: operations["listBranches"];
        put?: never;
        /** Propose a new branch or a change to an existing one (maker-checker) */
        post: operations["proposeBranch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/holidays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List holidays */
        get: operations["listHolidays"];
        put?: never;
        /** Propose one or more holidays (maker-checker) */
        post: operations["proposeHolidays"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tax-rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tax rates */
        get: operations["listTaxRates"];
        put?: never;
        /** Propose tax rate */
        post: operations["proposeTaxRate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enumerations/{type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get enumeration */
        get: operations["getEnumeration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List approvals */
        get: operations["listApprovals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get approval */
        get: operations["getApproval"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject */
        post: operations["reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/bulk-approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk approve */
        post: operations["bulkApprove"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search customers */
        get: operations["searchCustomers"];
        put?: never;
        /** Create a customer (maker-checker). Returns the existing customer when PAN already exists (idempotent create). */
        post: operations["createCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/dedupe-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dedupe check */
        post: operations["dedupeCheck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get customer */
        get: operations["getCustomer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gl/heads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List gl heads */
        get: operations["listGlHeads"];
        put?: never;
        /** Propose gl head */
        post: operations["proposeGlHead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gl/vouchers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List vouchers */
        get: operations["listVouchers"];
        put?: never;
        /** Propose a manual voucher (contra, receipt, payment, journal; any number of lines) */
        post: operations["proposeVoucher"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gl/vouchers/{id}/reverse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Propose voucher reversal */
        post: operations["proposeVoucherReversal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gl/trial-balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trial balance */
        get: operations["trialBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gl/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Drill-down from a GL head to its entries */
        get: operations["glEntries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gl/profit-and-loss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profit and loss */
        get: operations["profitAndLoss"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gl/balance-sheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Balance sheet */
        get: operations["balanceSheet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eod/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List eod runs */
        get: operations["listEodRuns"];
        put?: never;
        /** Start end-of-day for the current business date (single instance per tenant) */
        post: operations["startEod"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eod/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get eod run */
        get: operations["getEodRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eod/runs/{runId}/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restart eod */
        post: operations["restartEod"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eod/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get eod schedule */
        get: operations["getEodSchedule"];
        /** Propose eod schedule */
        put: operations["proposeEodSchedule"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List audit events */
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify audit chain */
        get: operations["verifyAuditChain"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loan-products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Loan products with fee rules */
        get: operations["listLoanProducts"];
        put?: never;
        /** Create or change a product (maker-checker; approval bumps the version) */
        post: operations["proposeLoanProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loan-products/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One loan product */
        get: operations["getLoanProduct"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loans/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Schedule, fees, net disbursal and APR from the same engine that posts (KFS figures) */
        post: operations["previewLoan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search loans by number, customer, name or LOS reference */
        get: operations["searchLoans"];
        put?: never;
        /** Book a loan as SANCTIONED (idempotent on externalRef); money moves at disbursement */
        post: operations["createLoan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loans/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Loan with balances, DPD and asset class */
        get: operations["getLoan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loans/{id}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Demands raised, charges and the future schedule */
        get: operations["getLoanSchedule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loans/{id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Financial transactions (newest first); day-end accruals are not listed */
        get: operations["getLoanTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loans/{id}/kfs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Key Fact Statement as generated at booking */
        get: operations["getLoanKfs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loans/{id}/kfs-acceptance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record the borrower's KFS acceptance (required before disbursement) */
        post: operations["acceptLoanKfs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loans/{id}/disbursement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Staff users get a 202 approval; LOS clients with loan:stp are disbursed immediately (200) */
        post: operations["disburseLoan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loans/{id}/repayments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Receipt appropriated per product sequence; any excess is kept as an advance */
        post: operations["repayLoan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loans/{id}/prepayments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Part-prepayment; the schedule is rebuilt (reduce EMI or reduce tenure) */
        post: operations["prepayLoan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loans/{id}/preclosure-quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pre-closure amount today (the posting uses the same figures) */
        get: operations["getPreclosureQuote"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loans/{id}/preclosure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close the loan; amount must equal the quote total */
        post: operations["precloseLoan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loans/{id}/cancellation-quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Amount to exit within the cooling-off period */
        get: operations["getCancellationQuote"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loans/{id}/cancellation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cooling-off exit (principal + interest for days used; disclosed fees retained) */
        post: operations["cancelLoan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loans/{id}/charges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Charge a product fee (with GST) to the loan */
        post: operations["chargeLoanFee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loans/{id}/charges/{chargeId}/waiver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Propose a waiver of an unpaid charge (maker-checker) */
        post: operations["waiveLoanCharge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loans/{id}/transactions/{txnId}/reverse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Propose reversal of a transaction and every later one; days since are replayed (maker-checker) */
        post: operations["reverseLoanTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loans/{id}/freeze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Block transactions (accrual continues) */
        post: operations["freezeLoan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loans/{id}/unfreeze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Allow transactions again */
        post: operations["unfreezeLoan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform/v1/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tenants */
        get: operations["listTenants"];
        put?: never;
        /** Provision a tenant (database, migrations, starter kit, first admin) */
        post: operations["provisionTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform/v1/tenants/{code}/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set tenant modules */
        put: operations["setTenantModules"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform/v1/migrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Migrate all tenants */
        post: operations["migrateAllTenants"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @example 100000.00 */
        Money: string;
        Problem: {
            type?: string;
            title?: string;
            status?: number;
            detail?: string;
            instance?: string;
        };
        Me: {
            userId: string;
            displayName: string;
            tenant: string;
            tenantName?: string;
            homeBranch?: string;
            /** Format: date */
            businessDate: string;
            permissions: string[];
            modules: string[];
        };
        BusinessDay: {
            /** Format: date */
            businessDate: string;
            /** @enum {string} */
            status: "OPEN" | "EOD_RUNNING" | "EOD_FAILED" | "CLOSED";
        };
        Branch: {
            code: string;
            name: string;
            ifsc?: string | null;
            /** @description GST state code, e.g. 32 */
            stateCode: string;
            parentCode?: string | null;
            headOffice?: boolean;
            /** @enum {string} */
            status?: "ACTIVE" | "CLOSED";
        };
        Holiday: {
            /** @description null = all branches */
            branchCode?: string | null;
            /** Format: date */
            day: string;
            reason: string;
        };
        TaxRate: {
            /** @example GST18 */
            code: string;
            /** @enum {string} */
            taxType: "GST" | "TDS";
            /** @example 18.00 */
            ratePercent: string;
            /** Format: date */
            effectiveFrom: string;
            /** Format: date */
            effectiveTo?: string | null;
        };
        EnumValue: {
            code: string;
            label: string;
            active?: boolean;
        };
        /** @enum {string} */
        ApprovalStatus: "PENDING" | "APPROVED" | "REJECTED" | "WITHDRAWN";
        Approval: {
            /** Format: uuid */
            id: string;
            /**
             * @example CUSTOMER
             * @example BRANCH
             * @example GL_HEAD
             * @example VOUCHER
             * @example TAX_RATE
             * @example HOLIDAY
             * @example EOD_SCHEDULE
             */
            entityType: string;
            entityId?: string | null;
            /**
             * @example CREATE
             * @example UPDATE
             * @example REVERSE
             */
            action: string;
            status: components["schemas"]["ApprovalStatus"];
            maker: string;
            /** Format: date-time */
            madeAt: string;
            checker?: string | null;
            /** Format: date-time */
            checkedAt?: string | null;
            note?: string | null;
            amount?: components["schemas"]["Money"] | null;
            /** @description SLA ageing */
            ageHours?: number;
            /** @description State before the change (null for CREATE) */
            current?: Record<string, never> | null;
            /** @description Proposed state */
            proposed?: Record<string, never>;
        };
        Decision: {
            note?: string;
        };
        CustomerInput: {
            /** @enum {string} */
            customerType: "INDIVIDUAL" | "NON_INDIVIDUAL";
            firstName: string;
            middleName?: string;
            lastName?: string;
            /** Format: date */
            dateOfBirth: string;
            /** @enum {string} */
            gender?: "FEMALE" | "MALE" | "OTHER";
            pan?: string;
            mobile: string;
            /** Format: email */
            email?: string;
            homeBranch: string;
            address?: {
                line1?: string;
                line2?: string;
                city?: string;
                stateCode?: string;
                pincode?: string;
            };
            /** @description Proceed despite possible duplicates (requires approval with reason) */
            overrideDedupe?: boolean;
            overrideReason?: string;
        };
        CustomerSummary: {
            /** Format: uuid */
            id: string;
            customerNo: string;
            displayName: string;
            customerType?: string;
            /** Format: date */
            dateOfBirth?: string;
            /** @example XXXXX1234X */
            panMasked?: string | null;
            /** @example XXXXXX0001 */
            mobileMasked?: string | null;
            homeBranch?: string;
            kycStatus?: string;
            status: string;
        };
        DedupeMatch: {
            customerNo: string;
            displayName: string;
            /** @enum {string} */
            rule: "PAN" | "MOBILE" | "NAME_DOB";
            /** @enum {string} */
            strength?: "EXACT" | "STRONG" | "POSSIBLE";
        };
        GlHead: {
            code: string;
            name: string;
            /** @enum {string} */
            category: "ASSET" | "LIABILITY" | "EQUITY" | "INCOME" | "EXPENSE";
            parentCode?: string | null;
            /** @description Only posting (leaf) heads accept entries */
            posting: boolean;
            /** @enum {string} */
            status?: "ACTIVE" | "FROZEN" | "CLOSED";
        };
        VoucherLine: {
            branch: string;
            glCode: string;
            /** @description Defaults to glCode */
            account?: string;
            /** @enum {string} */
            side: "DR" | "CR";
            amount: components["schemas"]["Money"];
            narration?: string;
        };
        VoucherInput: {
            /** @enum {string} */
            voucherType: "CONTRA" | "RECEIPT" | "PAYMENT" | "JOURNAL";
            /** Format: date */
            valueDate: string;
            reference?: string;
            description: string;
            lines: components["schemas"]["VoucherLine"][];
        };
        Voucher: components["schemas"]["VoucherInput"] & {
            /** Format: uuid */
            id: string;
            voucherNo: string;
            /** @enum {string} */
            status: "POSTED" | "REVERSED";
            amount: components["schemas"]["Money"];
            /** Format: uuid */
            lotId?: string;
            /** Format: uuid */
            reversalLotId?: string | null;
            /** Format: date */
            businessDate?: string;
        };
        TrialBalanceRow: {
            glCode: string;
            glName: string;
            category: string;
            debit: components["schemas"]["Money"];
            credit: components["schemas"]["Money"];
            net: components["schemas"]["Money"];
        };
        LedgerEntry: {
            /** Format: uuid */
            lotId?: string;
            /** Format: date */
            businessDate?: string;
            branch?: string;
            glCode?: string;
            account?: string;
            /** @enum {string} */
            side?: "DR" | "CR";
            amount?: components["schemas"]["Money"];
            narration?: string;
            lotType?: string;
        };
        StatementRow: {
            /**
             * @example INCOME
             * @example EXPENSE
             * @example ASSET
             * @example LIABILITY
             * @example EQUITY
             * @example NET_PROFIT
             */
            section: string;
            glCode: string;
            glName: string;
            amount: components["schemas"]["Money"];
        };
        EodStep: {
            stepNo?: number;
            name?: string;
            /** @enum {string} */
            status?: "PENDING" | "RUNNING" | "COMPLETED" | "COMPLETED_WITH_EXCEPTIONS" | "FAILED" | "SKIPPED";
            processed?: number;
            failed?: number;
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            finishedAt?: string | null;
        };
        EodException: {
            step?: string;
            accountNo?: string;
            error?: string;
            resolved?: boolean;
        };
        EodRun: {
            /** Format: int64 */
            id: number;
            /** Format: date */
            businessDate: string;
            /** @enum {string} */
            status: "RUNNING" | "COMPLETED" | "COMPLETED_WITH_EXCEPTIONS" | "FAILED";
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            finishedAt?: string | null;
            /** Format: date */
            nextBusinessDate?: string | null;
            steps?: components["schemas"]["EodStep"][];
            exceptions?: components["schemas"]["EodException"][];
        };
        EodSchedule: {
            /** @enum {string} */
            mode: "MANUAL" | "SCHEDULED";
            /** @example 0 30 23 * * * */
            cron?: string | null;
            alertEmails?: string[];
        };
        AuditEvent: {
            /** Format: int64 */
            id?: number;
            /** Format: date-time */
            at?: string;
            actor?: string;
            action?: string;
            entityType?: string;
            entityId?: string | null;
            detail?: Record<string, never> | null;
        };
        TenantInput: {
            code: string;
            legalName: string;
            /** @enum {string} */
            entityType: "NBFC" | "BANK" | "SFB" | "COOP_BANK" | "HFC" | "MFI";
            /** @enum {string} */
            deploymentTier: "POOLED" | "DEDICATED" | "STANDALONE";
            /** @enum {string} */
            edition: "STARTER" | "GROWTH" | "ENTERPRISE";
            /**
             * @default NBFC
             * @enum {string}
             */
            starterKit: "NBFC" | "BANK";
            headOffice?: {
                code: string;
                name: string;
                stateCode: string;
            };
            /** Format: date */
            firstBusinessDate?: string;
        };
        Tenant: {
            /** Format: uuid */
            id?: string;
            code?: string;
            legalName?: string;
            entityType?: string;
            deploymentTier?: string;
            edition?: string;
            status?: string;
            modules?: string[];
        };
        MigrationResult: {
            tenant?: string;
            currentVersion?: string | null;
            pending?: string[];
            /** @enum {string} */
            status?: "UP_TO_DATE" | "PENDING" | "MIGRATED" | "FAILED";
            error?: string | null;
        };
        /** @enum {string} */
        LoanStatus: "SANCTIONED" | "ACTIVE" | "FROZEN" | "CLOSED" | "CANCELLED" | "WRITTEN_OFF";
        /** @enum {string} */
        AssetClass: "STANDARD" | "SMA0" | "SMA1" | "SMA2" | "SUBSTANDARD" | "DOUBTFUL1" | "DOUBTFUL2" | "DOUBTFUL3" | "LOSS";
        AmountBody: {
            amount: components["schemas"]["Money"];
        };
        ReasonBody: {
            reason: string;
        };
        FeeRule: {
            code: string;
            name: string;
            /** @enum {string} */
            event: "DISBURSEMENT" | "PRECLOSURE" | "PART_PREPAYMENT" | "BOUNCE" | "LATE_PAYMENT" | "CANCELLATION" | "ADHOC";
            /** @enum {string} */
            calcType: "FIXED" | "PERCENT" | "SLAB";
            amount?: number | string | null;
            percent?: number | string | null;
            slabs?: {
                from?: number | string;
                to?: number | string;
                fee?: number | string;
            }[];
            minAmount?: number | string | null;
            maxAmount?: number | string | null;
            /** @default 18 */
            gstRate: number | string | null;
            /** @enum {string} */
            taxTreatment?: "EXCLUSIVE" | "INCLUSIVE";
            deductFromDisbursal?: boolean;
        };
        LoanProduct: {
            code: string;
            name: string;
            /** @enum {string} */
            repaymentMethod: "EQUATED" | "FIXED_PRINCIPAL" | "BULLET_TOTAL_INTEREST" | "BULLET_PERIODIC_INTEREST";
            minAmount: number | string;
            maxAmount: number | string;
            minTenorMonths: number;
            maxTenorMonths: number;
            minRate: number | string;
            maxRate: number | string;
            interestTableCode?: string | null;
            /** @enum {string} */
            rateType?: "FIXED" | "FLOATING";
            /** @enum {string} */
            dayCount?: "ACTUAL_365" | "ACTUAL_360" | "ACTUAL_ACTUAL" | "THIRTY_360";
            /** @enum {string} */
            rounding?: "RUPEE_HALF_UP" | "RUPEE_DOWN" | "RUPEE_UP" | "PAISE_HALF_UP" | "PAISE_HALF_EVEN";
            penalChargeRate?: number | string | null;
            maxMoratoriumMonths?: number;
            coolingOffDays?: number;
            secured?: boolean;
            appropriationSequence?: ("INTEREST" | "PRINCIPAL" | "PENAL" | "FEE")[];
            /** @enum {string} */
            appropriationMode?: "BY_DEMAND" | "BY_COMPONENT";
            /** @enum {string} */
            prepaymentMode?: "REDUCE_EMI" | "REDUCE_TENURE";
            /** @enum {string} */
            status?: "DRAFT" | "ACTIVE" | "WITHDRAWN";
            fees?: components["schemas"]["FeeRule"][];
            readonly version?: number;
        };
        LoanApplication: {
            productCode: string;
            /** Format: uuid */
            customerId: string;
            /** @description Defaults to the customer's home branch */
            branch?: string;
            amount: number | string;
            tenorMonths: number;
            /** @description Omit to use the product interest table */
            rate?: number | string | null;
            /** Format: date */
            disbursalDate?: string;
            /** Format: date */
            firstDueDate?: string;
            moratoriumMonths?: number;
            balloon?: number | string | null;
            securedPortion?: number | string | null;
            /** @description LOS application id; repeating it returns the existing loan */
            externalRef?: string;
        };
        ScheduleRow: {
            instalmentNo?: number;
            /** Format: date */
            dueDate?: string;
            days?: number;
            openingBalance?: components["schemas"]["Money"];
            interest?: components["schemas"]["Money"];
            principal?: components["schemas"]["Money"];
            instalment?: components["schemas"]["Money"];
            closingBalance?: components["schemas"]["Money"];
        };
        LoanKfs: {
            productCode?: string;
            productName?: string;
            productVersion?: number;
            amount?: components["schemas"]["Money"];
            tenorMonths?: number;
            repaymentMethod?: string;
            rateType?: string;
            interestRate?: string;
            rateExplanation?: string;
            emi?: string | null;
            instalments?: number;
            totalInterest?: components["schemas"]["Money"];
            fees?: {
                code?: string;
                name?: string;
                fee?: string;
                cgst?: string;
                sgst?: string;
                igst?: string;
                total?: string;
            }[];
            netDisbursal?: components["schemas"]["Money"];
            totalRepayable?: components["schemas"]["Money"];
            /** @description Annual percentage rate (IRR of net flows, fees ex-GST) */
            apr?: string;
            penalChargeRate?: string | null;
            penalChargeNote?: string;
            coolingOffDays?: number;
            placeOfSupply?: string;
            schedule?: components["schemas"]["ScheduleRow"][];
        };
        LoanSummary: {
            /** Format: uuid */
            id?: string;
            loanNo?: string;
            customerName?: string;
            customerNo?: string;
            productCode?: string;
            status?: components["schemas"]["LoanStatus"];
            amount?: components["schemas"]["Money"];
            principalOutstanding?: components["schemas"]["Money"];
            overdueAmount?: components["schemas"]["Money"];
            dpd?: number;
            assetClass?: components["schemas"]["AssetClass"];
            /** Format: date */
            nextDueDate?: string | null;
            branch?: string;
        };
        Loan: components["schemas"]["LoanSummary"] & {
            /** Format: uuid */
            customerId?: string;
            productVersion?: number;
            rate?: string;
            tenorMonths?: number;
            repaymentMethod?: string;
            emi?: string | null;
            apr?: string | null;
            /** Format: date */
            openDate?: string;
            /** Format: date */
            disbursedOn?: string | null;
            netDisbursed?: string | null;
            /** Format: date */
            npaSince?: string | null;
            provisionHeld?: string;
            /** Format: date-time */
            kfsAcceptedAt?: string | null;
            externalRef?: string | null;
            /** Format: date */
            closedOn?: string | null;
        };
        LoanSchedule: {
            demands?: {
                instalmentNo?: number;
                /** Format: date */
                dueDate?: string;
                principalDue?: string;
                interestDue?: string;
                principalPaid?: string;
                interestPaid?: string;
            }[];
            charges?: {
                id?: string;
                code?: string;
                name?: string;
                /** @enum {string} */
                kind?: "FEE" | "PENAL";
                /** Format: date */
                date?: string;
                amount?: string;
                paid?: string;
                waived?: string;
                unpaid?: string;
            }[];
            future?: components["schemas"]["ScheduleRow"][];
            accruedInterest?: string;
            advance?: string;
        };
        LoanTxn: {
            /** Format: uuid */
            id?: string;
            seq?: number;
            /**
             * @example DISBURSEMENT
             * @example REPAYMENT
             * @example PREPAYMENT
             * @example PRECLOSURE
             * @example CANCELLATION
             * @example FEE_CHARGE
             * @example WAIVER
             * @example REVERSAL
             * @example FREEZE
             */
            type?: string;
            /** Format: date */
            valueDate?: string;
            /** Format: date */
            businessDate?: string;
            amount?: string | null;
            summary?: string;
            /** Format: uuid */
            reversedBy?: string | null;
            /** Format: uuid */
            reverses?: string | null;
            createdBy?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        PreclosureQuote: {
            /** Format: date */
            asOf?: string;
            principal?: string;
            overdueDues?: string;
            accruedInterest?: string;
            charges?: string;
            foreclosureFee?: string;
            advanceAdjusted?: string;
            total?: string;
        };
    };
    responses: {
        /** @description Change recorded as an approval request; applied when a checker approves it */
        Accepted: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Approval"];
            };
        };
        /** @description Error */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        Id: string;
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getBusinessDay: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessDay"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listBranches: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Branch"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    proposeBranch: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Branch"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            default: components["responses"]["Problem"];
        };
    };
    listHolidays: {
        parameters: {
            query: {
                year: number;
                branch?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Holiday"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    proposeHolidays: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Holiday"][];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            default: components["responses"]["Problem"];
        };
    };
    listTaxRates: {
        parameters: {
            query?: {
                asOf?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxRate"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    proposeTaxRate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaxRate"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            default: components["responses"]["Problem"];
        };
    };
    getEnumeration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnumValue"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listApprovals: {
        parameters: {
            query?: {
                status?: components["schemas"]["ApprovalStatus"];
                entityType?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Approval"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getApproval: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Approval with current vs proposed state for the checker's diff view */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Approval"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Decision"];
            };
        };
        responses: {
            /** @description Approved and applied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Approval"];
                };
            };
            409: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Decision"];
            };
        };
        responses: {
            /** @description Rejected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Approval"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    bulkApprove: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    ids: string[];
                    note?: string;
                };
            };
        };
        responses: {
            /** @description Per-item result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id?: string;
                        ok?: boolean;
                        error?: string;
                    }[];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    searchCustomers: {
        parameters: {
            query?: {
                /** @description Customer number, exact PAN or exact mobile */
                q?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Masked customer summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerSummary"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createCustomer: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerInput"];
            };
        };
        responses: {
            /** @description Customer with this PAN already exists */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerSummary"];
                };
            };
            202: components["responses"]["Accepted"];
            default: components["responses"]["Problem"];
        };
    };
    dedupeCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerInput"];
            };
        };
        responses: {
            /** @description Possible duplicates with the matching rule */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DedupeMatch"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Masked customer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerSummary"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listGlHeads: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chart of accounts (flat; build the tree from parentCode) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlHead"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    proposeGlHead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GlHead"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            default: components["responses"]["Problem"];
        };
    };
    listVouchers: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Voucher"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    proposeVoucher: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoucherInput"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            default: components["responses"]["Problem"];
        };
    };
    proposeVoucherReversal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Decision"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            default: components["responses"]["Problem"];
        };
    };
    trialBalance: {
        parameters: {
            query: {
                asOf: string;
                branch?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrialBalanceRow"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    glEntries: {
        parameters: {
            query: {
                glCode: string;
                from: string;
                to: string;
                branch?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerEntry"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    profitAndLoss: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatementRow"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    balanceSheet: {
        parameters: {
            query: {
                asOf: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatementRow"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listEodRuns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Most recent first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EodRun"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    startEod: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EodRun"];
                };
            };
            409: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getEodRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run with steps and exceptions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EodRun"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    restartEod: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Restarted from the first incomplete step */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EodRun"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getEodSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EodSchedule"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    proposeEodSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EodSchedule"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            default: components["responses"]["Problem"];
        };
    };
    listAuditEvents: {
        parameters: {
            query?: {
                entityType?: string;
                entityId?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Most recent first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEvent"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    verifyAuditChain: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chain verification result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        intact: boolean;
                        /** Format: int64 */
                        firstBrokenId?: number | null;
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listLoanProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoanProduct"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    proposeLoanProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoanProduct"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            default: components["responses"]["Problem"];
        };
    };
    getLoanProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoanProduct"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    previewLoan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoanApplication"];
            };
        };
        responses: {
            /** @description KFS figures */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoanKfs"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    searchLoans: {
        parameters: {
            query?: {
                q?: string;
                status?: components["schemas"]["LoanStatus"];
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoanSummary"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createLoan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoanApplication"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Loan"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getLoan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Loan"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getLoanSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoanSchedule"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getLoanTransactions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoanTxn"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getLoanKfs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoanKfs"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    acceptLoanKfs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @example OTP
                     * @example ESIGN
                     * @example BRANCH
                     */
                    channel?: string;
                    evidenceRef?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Loan"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    disburseLoan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    beneficiaryName?: string;
                    beneficiaryAccount?: string;
                    ifsc?: string;
                    /**
                     * @example IMPS
                     * @example NEFT
                     * @example CASH
                     */
                    mode?: string;
                };
            };
        };
        responses: {
            /** @description Disbursed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Loan"];
                };
            };
            202: components["responses"]["Accepted"];
            default: components["responses"]["Problem"];
        };
    };
    repayLoan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    amount: components["schemas"]["Money"];
                    /** Format: date */
                    valueDate?: string;
                    /**
                     * @example CASH
                     * @example NACH
                     * @example UPI
                     * @example NEFT
                     */
                    mode?: string;
                    reference?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Loan"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    prepayLoan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    amount: components["schemas"]["Money"];
                    /** @enum {string} */
                    mode?: "REDUCE_EMI" | "REDUCE_TENURE";
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Loan"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getPreclosureQuote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreclosureQuote"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    precloseLoan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AmountBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Loan"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getCancellationQuote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        total?: components["schemas"]["Money"];
                        /** Format: date */
                        asOf?: string;
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    cancelLoan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AmountBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Loan"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    chargeLoanFee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    feeCode: string;
                    base?: components["schemas"]["Money"];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Loan"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    waiveLoanCharge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                chargeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    amount: components["schemas"]["Money"];
                    reason: string;
                };
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            default: components["responses"]["Problem"];
        };
    };
    reverseLoanTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                txnId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonBody"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            default: components["responses"]["Problem"];
        };
    };
    freezeLoan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Loan"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    unfreezeLoan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Loan"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listTenants: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    provisionTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantInput"];
            };
        };
        responses: {
            /** @description Provisioned */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    setTenantModules: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    migrateAllTenants: {
        parameters: {
            query?: {
                dryRun?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-tenant result; one failure does not stop the others */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationResult"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
