/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user, tenant, business date, permissions and enabled modules */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/business-day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get business day */
        get: operations["getBusinessDay"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List branches */
        get: operations["listBranches"];
        put?: never;
        /** Propose a new branch or a change to an existing one (maker-checker) */
        post: operations["proposeBranch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/holidays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List holidays */
        get: operations["listHolidays"];
        put?: never;
        /** Propose one or more holidays (maker-checker) */
        post: operations["proposeHolidays"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tax-rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tax rates */
        get: operations["listTaxRates"];
        put?: never;
        /** Propose tax rate */
        post: operations["proposeTaxRate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enumerations/{type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get enumeration */
        get: operations["getEnumeration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List approvals */
        get: operations["listApprovals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get approval */
        get: operations["getApproval"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject */
        post: operations["reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/bulk-approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk approve */
        post: operations["bulkApprove"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search customers */
        get: operations["searchCustomers"];
        put?: never;
        /** Create a customer (maker-checker). Returns the existing customer when PAN already exists (idempotent create). */
        post: operations["createCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/dedupe-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dedupe check */
        post: operations["dedupeCheck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get customer */
        get: operations["getCustomer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gl/heads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List gl heads */
        get: operations["listGlHeads"];
        put?: never;
        /** Propose gl head */
        post: operations["proposeGlHead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gl/vouchers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List vouchers */
        get: operations["listVouchers"];
        put?: never;
        /** Propose a manual voucher (contra, receipt, payment, journal; any number of lines) */
        post: operations["proposeVoucher"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gl/vouchers/{id}/reverse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Propose voucher reversal */
        post: operations["proposeVoucherReversal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gl/trial-balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trial balance */
        get: operations["trialBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gl/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Drill-down from a GL head to its entries */
        get: operations["glEntries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gl/profit-and-loss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profit and loss */
        get: operations["profitAndLoss"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gl/balance-sheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Balance sheet */
        get: operations["balanceSheet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eod/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List eod runs */
        get: operations["listEodRuns"];
        put?: never;
        /** Start end-of-day for the current business date (single instance per tenant) */
        post: operations["startEod"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eod/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get eod run */
        get: operations["getEodRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eod/runs/{runId}/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restart eod */
        post: operations["restartEod"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eod/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get eod schedule */
        get: operations["getEodSchedule"];
        /** Propose eod schedule */
        put: operations["proposeEodSchedule"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List audit events */
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify audit chain */
        get: operations["verifyAuditChain"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform/v1/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tenants */
        get: operations["listTenants"];
        put?: never;
        /** Provision a tenant (database, migrations, starter kit, first admin) */
        post: operations["provisionTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform/v1/tenants/{code}/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set tenant modules */
        put: operations["setTenantModules"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform/v1/migrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Migrate all tenants */
        post: operations["migrateAllTenants"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @example 100000.00 */
        Money: string;
        Problem: {
            type?: string;
            title?: string;
            status?: number;
            detail?: string;
            instance?: string;
        };
        Me: {
            userId: string;
            displayName: string;
            tenant: string;
            tenantName?: string;
            homeBranch?: string;
            /** Format: date */
            businessDate: string;
            permissions: string[];
            modules: string[];
        };
        BusinessDay: {
            /** Format: date */
            businessDate: string;
            /** @enum {string} */
            status: "OPEN" | "EOD_RUNNING" | "EOD_FAILED" | "CLOSED";
        };
        Branch: {
            code: string;
            name: string;
            ifsc?: string | null;
            /** @description GST state code, e.g. 32 */
            stateCode: string;
            parentCode?: string | null;
            headOffice?: boolean;
            /** @enum {string} */
            status?: "ACTIVE" | "CLOSED";
        };
        Holiday: {
            /** @description null = all branches */
            branchCode?: string | null;
            /** Format: date */
            day: string;
            reason: string;
        };
        TaxRate: {
            /** @example GST18 */
            code: string;
            /** @enum {string} */
            taxType: "GST" | "TDS";
            /** @example 18.00 */
            ratePercent: string;
            /** Format: date */
            effectiveFrom: string;
            /** Format: date */
            effectiveTo?: string | null;
        };
        EnumValue: {
            code: string;
            label: string;
            active?: boolean;
        };
        /** @enum {string} */
        ApprovalStatus: "PENDING" | "APPROVED" | "REJECTED" | "WITHDRAWN";
        Approval: {
            /** Format: uuid */
            id: string;
            /**
             * @example CUSTOMER
             * @example BRANCH
             * @example GL_HEAD
             * @example VOUCHER
             * @example TAX_RATE
             * @example HOLIDAY
             * @example EOD_SCHEDULE
             */
            entityType: string;
            entityId?: string | null;
            /**
             * @example CREATE
             * @example UPDATE
             * @example REVERSE
             */
            action: string;
            status: components["schemas"]["ApprovalStatus"];
            maker: string;
            /** Format: date-time */
            madeAt: string;
            checker?: string | null;
            /** Format: date-time */
            checkedAt?: string | null;
            note?: string | null;
            amount?: components["schemas"]["Money"] | null;
            /** @description SLA ageing */
            ageHours?: number;
            /** @description State before the change (null for CREATE) */
            current?: Record<string, never> | null;
            /** @description Proposed state */
            proposed?: Record<string, never>;
        };
        Decision: {
            note?: string;
        };
        CustomerInput: {
            /** @enum {string} */
            customerType: "INDIVIDUAL" | "NON_INDIVIDUAL";
            firstName: string;
            middleName?: string;
            lastName?: string;
            /** Format: date */
            dateOfBirth: string;
            /** @enum {string} */
            gender?: "FEMALE" | "MALE" | "OTHER";
            pan?: string;
            mobile: string;
            /** Format: email */
            email?: string;
            homeBranch: string;
            address?: {
                line1?: string;
                line2?: string;
                city?: string;
                stateCode?: string;
                pincode?: string;
            };
            /** @description Proceed despite possible duplicates (requires approval with reason) */
            overrideDedupe?: boolean;
            overrideReason?: string;
        };
        CustomerSummary: {
            /** Format: uuid */
            id: string;
            customerNo: string;
            displayName: string;
            customerType?: string;
            /** Format: date */
            dateOfBirth?: string;
            /** @example XXXXX1234X */
            panMasked?: string | null;
            /** @example XXXXXX0001 */
            mobileMasked?: string | null;
            homeBranch?: string;
            kycStatus?: string;
            status: string;
        };
        DedupeMatch: {
            customerNo: string;
            displayName: string;
            /** @enum {string} */
            rule: "PAN" | "MOBILE" | "NAME_DOB";
            /** @enum {string} */
            strength?: "EXACT" | "STRONG" | "POSSIBLE";
        };
        GlHead: {
            code: string;
            name: string;
            /** @enum {string} */
            category: "ASSET" | "LIABILITY" | "EQUITY" | "INCOME" | "EXPENSE";
            parentCode?: string | null;
            /** @description Only posting (leaf) heads accept entries */
            posting: boolean;
            /** @enum {string} */
            status?: "ACTIVE" | "FROZEN" | "CLOSED";
        };
        VoucherLine: {
            branch: string;
            glCode: string;
            /** @description Defaults to glCode */
            account?: string;
            /** @enum {string} */
            side: "DR" | "CR";
            amount: components["schemas"]["Money"];
            narration?: string;
        };
        VoucherInput: {
            /** @enum {string} */
            voucherType: "CONTRA" | "RECEIPT" | "PAYMENT" | "JOURNAL";
            /** Format: date */
            valueDate: string;
            reference?: string;
            description: string;
            lines: components["schemas"]["VoucherLine"][];
        };
        Voucher: components["schemas"]["VoucherInput"] & {
            /** Format: uuid */
            id: string;
            voucherNo: string;
            /** @enum {string} */
            status: "POSTED" | "REVERSED";
            amount: components["schemas"]["Money"];
            /** Format: uuid */
            lotId?: string;
            /** Format: uuid */
            reversalLotId?: string | null;
            /** Format: date */
            businessDate?: string;
        };
        TrialBalanceRow: {
            glCode: string;
            glName: string;
            category: string;
            debit: components["schemas"]["Money"];
            credit: components["schemas"]["Money"];
            net: components["schemas"]["Money"];
        };
        LedgerEntry: {
            /** Format: uuid */
            lotId?: string;
            /** Format: date */
            businessDate?: string;
            branch?: string;
            glCode?: string;
            account?: string;
            /** @enum {string} */
            side?: "DR" | "CR";
            amount?: components["schemas"]["Money"];
            narration?: string;
            lotType?: string;
        };
        StatementRow: {
            /**
             * @example INCOME
             * @example EXPENSE
             * @example ASSET
             * @example LIABILITY
             * @example EQUITY
             * @example NET_PROFIT
             */
            section: string;
            glCode: string;
            glName: string;
            amount: components["schemas"]["Money"];
        };
        EodStep: {
            stepNo?: number;
            name?: string;
            /** @enum {string} */
            status?: "PENDING" | "RUNNING" | "COMPLETED" | "COMPLETED_WITH_EXCEPTIONS" | "FAILED" | "SKIPPED";
            processed?: number;
            failed?: number;
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            finishedAt?: string | null;
        };
        EodException: {
            step?: string;
            accountNo?: string;
            error?: string;
            resolved?: boolean;
        };
        EodRun: {
            /** Format: int64 */
            id: number;
            /** Format: date */
            businessDate: string;
            /** @enum {string} */
            status: "RUNNING" | "COMPLETED" | "COMPLETED_WITH_EXCEPTIONS" | "FAILED";
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            finishedAt?: string | null;
            /** Format: date */
            nextBusinessDate?: string | null;
            steps?: components["schemas"]["EodStep"][];
            exceptions?: components["schemas"]["EodException"][];
        };
        EodSchedule: {
            /** @enum {string} */
            mode: "MANUAL" | "SCHEDULED";
            /** @example 0 30 23 * * * */
            cron?: string | null;
            alertEmails?: string[];
        };
        AuditEvent: {
            /** Format: int64 */
            id?: number;
            /** Format: date-time */
            at?: string;
            actor?: string;
            action?: string;
            entityType?: string;
            entityId?: string | null;
            detail?: Record<string, never> | null;
        };
        TenantInput: {
            code: string;
            legalName: string;
            /** @enum {string} */
            entityType: "NBFC" | "BANK" | "SFB" | "COOP_BANK" | "HFC" | "MFI";
            /** @enum {string} */
            deploymentTier: "POOLED" | "DEDICATED" | "STANDALONE";
            /** @enum {string} */
            edition: "STARTER" | "GROWTH" | "ENTERPRISE";
            /**
             * @default NBFC
             * @enum {string}
             */
            starterKit: "NBFC" | "BANK";
            headOffice?: {
                code: string;
                name: string;
                stateCode: string;
            };
            /** Format: date */
            firstBusinessDate?: string;
        };
        Tenant: {
            /** Format: uuid */
            id?: string;
            code?: string;
            legalName?: string;
            entityType?: string;
            deploymentTier?: string;
            edition?: string;
            status?: string;
            modules?: string[];
        };
        MigrationResult: {
            tenant?: string;
            currentVersion?: string | null;
            pending?: string[];
            /** @enum {string} */
            status?: "UP_TO_DATE" | "PENDING" | "MIGRATED" | "FAILED";
            error?: string | null;
        };
    };
    responses: {
        /** @description Change recorded as an approval request; applied when a checker approves it */
        Accepted: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Approval"];
            };
        };
        /** @description Error */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        Id: string;
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getBusinessDay: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessDay"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listBranches: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Branch"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    proposeBranch: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Branch"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            default: components["responses"]["Problem"];
        };
    };
    listHolidays: {
        parameters: {
            query: {
                year: number;
                branch?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Holiday"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    proposeHolidays: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Holiday"][];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            default: components["responses"]["Problem"];
        };
    };
    listTaxRates: {
        parameters: {
            query?: {
                asOf?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxRate"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    proposeTaxRate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaxRate"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            default: components["responses"]["Problem"];
        };
    };
    getEnumeration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnumValue"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listApprovals: {
        parameters: {
            query?: {
                status?: components["schemas"]["ApprovalStatus"];
                entityType?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Approval"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getApproval: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Approval with current vs proposed state for the checker's diff view */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Approval"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Decision"];
            };
        };
        responses: {
            /** @description Approved and applied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Approval"];
                };
            };
            409: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Decision"];
            };
        };
        responses: {
            /** @description Rejected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Approval"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    bulkApprove: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    ids: string[];
                    note?: string;
                };
            };
        };
        responses: {
            /** @description Per-item result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id?: string;
                        ok?: boolean;
                        error?: string;
                    }[];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    searchCustomers: {
        parameters: {
            query?: {
                /** @description Customer number, exact PAN or exact mobile */
                q?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Masked customer summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerSummary"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createCustomer: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerInput"];
            };
        };
        responses: {
            /** @description Customer with this PAN already exists */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerSummary"];
                };
            };
            202: components["responses"]["Accepted"];
            default: components["responses"]["Problem"];
        };
    };
    dedupeCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerInput"];
            };
        };
        responses: {
            /** @description Possible duplicates with the matching rule */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DedupeMatch"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Masked customer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerSummary"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listGlHeads: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chart of accounts (flat; build the tree from parentCode) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlHead"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    proposeGlHead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GlHead"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            default: components["responses"]["Problem"];
        };
    };
    listVouchers: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Voucher"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    proposeVoucher: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoucherInput"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            default: components["responses"]["Problem"];
        };
    };
    proposeVoucherReversal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Decision"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            default: components["responses"]["Problem"];
        };
    };
    trialBalance: {
        parameters: {
            query: {
                asOf: string;
                branch?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrialBalanceRow"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    glEntries: {
        parameters: {
            query: {
                glCode: string;
                from: string;
                to: string;
                branch?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerEntry"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    profitAndLoss: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatementRow"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    balanceSheet: {
        parameters: {
            query: {
                asOf: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatementRow"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listEodRuns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Most recent first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EodRun"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    startEod: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EodRun"];
                };
            };
            409: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getEodRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run with steps and exceptions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EodRun"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    restartEod: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Restarted from the first incomplete step */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EodRun"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getEodSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EodSchedule"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    proposeEodSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EodSchedule"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            default: components["responses"]["Problem"];
        };
    };
    listAuditEvents: {
        parameters: {
            query?: {
                entityType?: string;
                entityId?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Most recent first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEvent"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    verifyAuditChain: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chain verification result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        intact: boolean;
                        /** Format: int64 */
                        firstBrokenId?: number | null;
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listTenants: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    provisionTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantInput"];
            };
        };
        responses: {
            /** @description Provisioned */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    setTenantModules: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    migrateAllTenants: {
        parameters: {
            query?: {
                dryRun?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-tenant result; one failure does not stop the others */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationResult"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
