package com.corebanking.integration.internal;

import com.corebanking.audit.AuditLog;
import com.corebanking.integration.core.keycloak.ApiClientScopes;
import com.corebanking.integration.core.keycloak.KeycloakAdminApi;
import com.corebanking.integration.core.provider.ProviderException;
import com.corebanking.platform.ApiException;
import com.corebanking.platform.ApprovalApplier;
import com.corebanking.platform.ApprovalRequest;
import com.corebanking.platform.ApprovalService;
import com.corebanking.platform.BranchScope;
import com.corebanking.platform.CurrentUser;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import org.springframework.context.annotation.Lazy;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * OAuth2 API clients per tenant (US-120): client-credentials clients of an LOS or a partner, as Keycloak clients
 * in the tenant's realm.
 * <ul>
 *   <li>Create, scope change, secret rotation, disable and enable go through maker-checker (entity API_CLIENT).
 *       A client that holds, or would get, a money-moving scope needs two checkers.</li>
 *   <li>Scopes are the product's permissions from an allow-list ({@link ApiClientScopes}): never approval,
 *       administration or configuration.</li>
 *   <li>The client secret is generated by Keycloak and is never stored here. After the approval, the user who
 *       proposed the client (or the rotation) collects it once; collecting it generates it, so nobody — not the
 *       checker, not this database — has seen it before.</li>
 *   <li>Each client has a staff profile under its service-account login, with a home branch and a branch scope:
 *       the data filter (US-020) applies to an API client exactly as to a person.</li>
 * </ul>
 */
@Service
class ApiClientService {

    static final String ENTITY = "API_CLIENT";

    /** openapi.yaml#/components/schemas/ApiClientInput. */
    record Input(String clientId, String name, List<String> scopes, String homeBranch, Boolean allBranches) {}

    private final JdbcTemplate jdbc;
    private final ApprovalService approvals;
    private final ClientAdmin admin;
    private final BranchScope scope;
    private final AuditLog audit;

    ApiClientService(JdbcTemplate jdbc, ApprovalService approvals, ClientAdmin admin, BranchScope scope, AuditLog audit) {
        this.jdbc = jdbc;
        this.approvals = approvals;
        this.admin = admin;
        this.scope = scope;
        this.audit = audit;
    }

    private static List<String> scopes(List<String> given) {
        try {
            return ApiClientScopes.validate(given);
        } catch (IllegalArgumentException e) {
            throw ApiException.invalid(e.getMessage());
        }
    }

    @Transactional
    ApprovalRequest proposeCreate(Input in) {
        if (in == null || in.clientId() == null) throw ApiException.invalid("clientId is required");
        String clientId = in.clientId().trim().toLowerCase(Locale.ROOT);
        if (!clientId.startsWith("ext-")) clientId = "ext-" + clientId;           // our clients are recognisable in the realm
        try {
            KeycloakAdminApi.clientId(clientId);
        } catch (IllegalArgumentException e) {
            throw ApiException.invalid(e.getMessage());
        }
        if (clientId.length() > 54) throw ApiException.invalid("clientId is too long");
        if (in.name() == null || in.name().isBlank() || in.name().length() > 80) throw ApiException.invalid("name is required (at most 80 characters)");
        List<String> s = scopes(in.scopes());
        if (in.homeBranch() == null) throw ApiException.invalid("homeBranch is required");
        scope.require(in.homeBranch());
        boolean all = Boolean.TRUE.equals(in.allBranches());
        if (all && !scope.seesAll()) throw ApiException.forbidden("only a user with all-branch access can give a client all-branch access");
        if (!jdbc.queryForList("SELECT 1 FROM integration.api_client WHERE client_id = ?", clientId).isEmpty()) {
            throw ApiException.conflict("API client " + clientId + " already exists");
        }
        Map<String, Object> p = new LinkedHashMap<>();
        p.put("clientId", clientId);
        p.put("name", in.name().trim());
        p.put("scopes", s);
        p.put("sensitiveScopes", s.stream().filter(ApiClientScopes.SENSITIVE::contains).toList());
        p.put("homeBranch", in.homeBranch());
        p.put("allBranches", all);
        return approvals.propose(ENTITY, ApiClientScopes.action("CREATE", s), clientId, p, null, null, in.homeBranch(), null);
    }

    @Transactional
    ApprovalRequest proposeScopes(String clientId, List<String> given) {
        Map<String, Object> current = one(clientId);
        List<String> s = scopes(given);
        Map<String, Object> p = new LinkedHashMap<>();
        p.put("clientId", clientId);
        p.put("scopes", s);
        p.put("sensitiveScopes", s.stream().filter(ApiClientScopes.SENSITIVE::contains).toList());
        return approvals.propose(ENTITY, ApiClientScopes.action("SCOPE_CHANGE", s), clientId, p, current, null, (String) current.get("homeBranch"), null);
    }

    /** ROTATE_SECRET, DISABLE or ENABLE. A new secret for a client with money-moving scopes needs two checkers. */
    @Transactional
    ApprovalRequest proposeAction(String clientId, String action) {
        Map<String, Object> current = one(clientId);
        String a = action;
        if ("ROTATE_SECRET".equals(action)) {
            List<String> held = jdbc.queryForList("SELECT unnest(scopes) FROM integration.api_client WHERE client_id = ?", String.class, clientId);
            a = ApiClientScopes.action(action, held);
        }
        return approvals.propose(ENTITY, a, clientId, Map.of("clientId", clientId), current, null, (String) current.get("homeBranch"), null);
    }

    private static <T> T keycloak(java.util.function.Supplier<T> call) {
        try {
            return call.get();
        } catch (ProviderException e) {
            throw new ApiException(e.retryable() ? HttpStatus.SERVICE_UNAVAILABLE : HttpStatus.CONFLICT, "identity provider: " + e.getMessage());
        }
    }

    String apply(ApprovalRequest r) {
        String realm = CurrentUser.requireTenant();
        String clientId = String.valueOf(r.payload().get("clientId"));
        String action = r.action().replace("_SENSITIVE", "");
        List<String> s = r.payload().get("scopes") instanceof List<?> l ? scopes(l.stream().map(String::valueOf).toList()) : List.of();
        String array = "{" + String.join(",", s) + "}";
        switch (action) {
            case "CREATE" -> {
                String name = String.valueOf(r.payload().get("name"));
                ClientAdmin.Created c = keycloak(() -> admin.create(realm, clientId, name, s));
                String login = c.serviceUsername().toLowerCase(Locale.ROOT);
                jdbc.update("""
                        INSERT INTO integration.api_client (client_id, name, scopes, home_branch, all_branches, keycloak_id, service_username,
                                                            secret_pending_for, approval_id, created_by)
                        VALUES (?, ?, ?::text[], ?, ?, ?, ?, ?, ?, ?)
                        """, clientId, name, array, r.payload().get("homeBranch"), Boolean.TRUE.equals(r.payload().get("allBranches")), c.id(),
                        login, r.maker(), r.id(), r.maker());
                // the staff profile that gives the client its branch scope (as for the batch service account, V13)
                jdbc.update("""
                        INSERT INTO platform.staff_user (user_id, username, display_name, home_branch, all_branches)
                        VALUES (?, ?, ?, ?, ?) ON CONFLICT (user_id) DO UPDATE SET home_branch = EXCLUDED.home_branch,
                               all_branches = EXCLUDED.all_branches, status = 'ACTIVE'
                        """, login, login, "API client " + name, r.payload().get("homeBranch"), Boolean.TRUE.equals(r.payload().get("allBranches")));
            }
            case "SCOPE_CHANGE" -> {
                keycloak(() -> {
                    admin.setScopes(realm, keycloakId(clientId), s);
                    return null;
                });
                jdbc.update("UPDATE integration.api_client SET scopes = ?::text[], updated_at = now() WHERE client_id = ?", array, clientId);
            }
            case "ROTATE_SECRET" -> jdbc.update("UPDATE integration.api_client SET secret_pending_for = ?, updated_at = now() WHERE client_id = ?",
                    r.maker(), clientId);
            case "DISABLE", "ENABLE" -> {
                boolean enable = "ENABLE".equals(action);
                keycloak(() -> {
                    admin.setEnabled(realm, keycloakId(clientId), clientId, enable);
                    return null;
                });
                jdbc.update("UPDATE integration.api_client SET status = ?, secret_pending_for = NULL, updated_at = now() WHERE client_id = ?",
                        enable ? "ACTIVE" : "DISABLED", clientId);
                jdbc.update("UPDATE platform.staff_user SET status = ? WHERE user_id = (SELECT service_username FROM integration.api_client WHERE client_id = ?)",
                        enable ? "ACTIVE" : "SUSPENDED", clientId);
            }
            default -> throw ApiException.invalid("unknown action " + r.action());
        }
        audit.record(CurrentUser.username(), "API_CLIENT_" + action, ENTITY, clientId, Map.of("approvalId", r.id().toString()));
        return clientId;
    }

    private String keycloakId(String clientId) {
        List<String> ids = jdbc.queryForList("SELECT keycloak_id FROM integration.api_client WHERE client_id = ?", String.class, clientId);
        if (ids.isEmpty()) throw ApiException.notFound("API client " + clientId);
        return ids.get(0);
    }

    /**
     * Generates the client secret at the identity provider and returns it — once, to the user the approved request
     * named. It is not stored and cannot be read again; a lost secret means a new rotation.
     */
    @Transactional
    Map<String, Object> claimSecret(String clientId) {
        List<Map<String, Object>> rows = jdbc.queryForList(
                "SELECT secret_pending_for, status, keycloak_id FROM integration.api_client WHERE client_id = ? FOR UPDATE", clientId);
        if (rows.isEmpty()) throw ApiException.notFound("API client " + clientId);
        String user = CurrentUser.username();
        String pending = (String) rows.get(0).get("secret_pending_for");
        if (pending == null) throw ApiException.conflict("there is no secret to collect: propose a rotation first");
        if (!pending.equalsIgnoreCase(user)) throw ApiException.forbidden("the secret can be collected only by the user who proposed it");
        if (!"ACTIVE".equals(rows.get(0).get("status"))) throw ApiException.conflict("the client is disabled");
        jdbc.update("UPDATE integration.api_client SET secret_pending_for = NULL, secret_issued_at = now(), updated_at = now() WHERE client_id = ?", clientId);
        String secret = keycloak(() -> admin.newSecret(CurrentUser.requireTenant(), (String) rows.get(0).get("keycloak_id")));
        audit.record(user, "API_CLIENT_SECRET_ISSUED", ENTITY, clientId, Map.of());
        Map<String, Object> m = new LinkedHashMap<>();
        m.put("clientId", clientId);
        m.put("clientSecret", secret);
        m.put("grantType", "client_credentials");
        return m;
    }

    private static final String SELECT = """
            SELECT client_id AS "clientId", name, status, array_to_string(scopes, ',') AS scopes, home_branch AS "homeBranch",
                   all_branches AS "allBranches", service_username AS "serviceUsername", secret_pending_for IS NOT NULL AS "secretPending",
                   secret_issued_at AS "secretIssuedAt", created_by AS "createdBy", created_at AS "createdAt"
              FROM integration.api_client""";

    private static Map<String, Object> view(Map<String, Object> row) {
        Map<String, Object> m = new LinkedHashMap<>(row);
        m.put("scopes", List.of(String.valueOf(row.get("scopes")).split(",")));
        return m;
    }

    Map<String, Object> one(String clientId) {
        List<Map<String, Object>> rows = jdbc.queryForList(SELECT + " WHERE client_id = ?", clientId);
        if (rows.isEmpty()) throw ApiException.notFound("API client " + clientId);
        return view(rows.get(0));
    }

    List<Map<String, Object>> list() {
        return jdbc.queryForList(SELECT + " ORDER BY client_id").stream().map(ApiClientService::view).toList();
    }

    @Component
    static class Applier implements ApprovalApplier {
        private final ApiClientService clients;

        Applier(@Lazy ApiClientService clients) {
            this.clients = clients;
        }

        @Override public String entityType() { return ENTITY; }

        @Override public String apply(ApprovalRequest r) { return clients.apply(r); }
    }
}
